language: android
jdk: oraclejdk8
sudo: false

branches:
  only:
  - master

android:
  components:
  - tools
  - platform-tools
  - build-tools-28
  - android-28
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.2"

script: ./gradlew build assembleDebug
